2024-01-16 12:13:25 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/operar-eur-aud
2024-01-16 12:13:25 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55621974ff83 <unknown>
#1 0x556219408cf7 <unknown>
#2 0x55621945899e <unknown>
#3 0x556219458aa1 <unknown>
#4 0x5562194a3d64 <unknown>
#5 0x5562194820dd <unknown>
#6 0x5562194a1006 <unknown>
#7 0x556219481e53 <unknown>
#8 0x556219449dd4 <unknown>
#9 0x55621944b1de <unknown>
#10 0x556219714531 <unknown>
#11 0x556219718455 <unknown>
#12 0x556219700f55 <unknown>
#13 0x5562197190ef <unknown>
#14 0x5562196e499f <unknown>
#15 0x55621973d008 <unknown>
#16 0x55621973d1d7 <unknown>
#17 0x55621974f124 <unknown>
#18 0x7fd5aac94ac3 <unknown>

2024-01-16 12:13:30 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/operar-eur-aud
2024-01-16 12:13:30 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55621974ff83 <unknown>
#1 0x556219408cf7 <unknown>
#2 0x55621945899e <unknown>
#3 0x556219458aa1 <unknown>
#4 0x5562194a3d64 <unknown>
#5 0x5562194820dd <unknown>
#6 0x5562194a1006 <unknown>
#7 0x556219481e53 <unknown>
#8 0x556219449dd4 <unknown>
#9 0x55621944b1de <unknown>
#10 0x556219714531 <unknown>
#11 0x556219718455 <unknown>
#12 0x556219700f55 <unknown>
#13 0x5562197190ef <unknown>
#14 0x5562196e499f <unknown>
#15 0x55621973d008 <unknown>
#16 0x55621973d1d7 <unknown>
#17 0x55621974f124 <unknown>
#18 0x7fd5aac94ac3 <unknown>