2024-01-26 16:07:12 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/trade-stocks
2024-01-26 16:07:12 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x559c0bfc2f83 <unknown>
#1 0x559c0bc7bcf7 <unknown>
#2 0x559c0bccb99e <unknown>
#3 0x559c0bccbaa1 <unknown>
#4 0x559c0bd16d64 <unknown>
#5 0x559c0bcf50dd <unknown>
#6 0x559c0bd14006 <unknown>
#7 0x559c0bcf4e53 <unknown>
#8 0x559c0bcbcdd4 <unknown>
#9 0x559c0bcbe1de <unknown>
#10 0x559c0bf87531 <unknown>
#11 0x559c0bf8b455 <unknown>
#12 0x559c0bf73f55 <unknown>
#13 0x559c0bf8c0ef <unknown>
#14 0x559c0bf5799f <unknown>
#15 0x559c0bfb0008 <unknown>
#16 0x559c0bfb01d7 <unknown>
#17 0x559c0bfc2124 <unknown>
#18 0x7f0020494ac3 <unknown>

2024-01-26 16:07:37 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-01-26 16:07:37 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x559c0bfc2f83 <unknown>
#1 0x559c0bc7bcf7 <unknown>
#2 0x559c0bccb99e <unknown>
#3 0x559c0bccbaa1 <unknown>
#4 0x559c0bd16d64 <unknown>
#5 0x559c0bcf50dd <unknown>
#6 0x559c0bd14006 <unknown>
#7 0x559c0bcf4e53 <unknown>
#8 0x559c0bcbcdd4 <unknown>
#9 0x559c0bcbe1de <unknown>
#10 0x559c0bf87531 <unknown>
#11 0x559c0bf8b455 <unknown>
#12 0x559c0bf73f55 <unknown>
#13 0x559c0bf8c0ef <unknown>
#14 0x559c0bf5799f <unknown>
#15 0x559c0bfb0008 <unknown>
#16 0x559c0bfb01d7 <unknown>
#17 0x559c0bfc2124 <unknown>
#18 0x7f0020494ac3 <unknown>