2024-01-26 14:53:49 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fr/trading-apple
2024-01-26 14:53:49 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x561639793f83 <unknown>
#1 0x56163944ccf7 <unknown>
#2 0x56163949c99e <unknown>
#3 0x56163949caa1 <unknown>
#4 0x5616394e7d64 <unknown>
#5 0x5616394c60dd <unknown>
#6 0x5616394e5006 <unknown>
#7 0x5616394c5e53 <unknown>
#8 0x56163948ddd4 <unknown>
#9 0x56163948f1de <unknown>
#10 0x561639758531 <unknown>
#11 0x56163975c455 <unknown>
#12 0x561639744f55 <unknown>
#13 0x56163975d0ef <unknown>
#14 0x56163972899f <unknown>
#15 0x561639781008 <unknown>
#16 0x5616397811d7 <unknown>
#17 0x561639793124 <unknown>
#18 0x7f680ec94ac3 <unknown>

2024-01-26 14:53:58 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 14:53:58 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x561639793f83 <unknown>
#1 0x56163944ccf7 <unknown>
#2 0x56163949c99e <unknown>
#3 0x56163949caa1 <unknown>
#4 0x5616394e7d64 <unknown>
#5 0x5616394c60dd <unknown>
#6 0x5616394e5006 <unknown>
#7 0x5616394c5e53 <unknown>
#8 0x56163948ddd4 <unknown>
#9 0x56163948f1de <unknown>
#10 0x561639758531 <unknown>
#11 0x56163975c455 <unknown>
#12 0x561639744f55 <unknown>
#13 0x56163975d0ef <unknown>
#14 0x56163972899f <unknown>
#15 0x561639781008 <unknown>
#16 0x5616397811d7 <unknown>
#17 0x561639793124 <unknown>
#18 0x7f680ec94ac3 <unknown>

2024-01-26 14:54:04 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 14:54:04 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x561639793f83 <unknown>
#1 0x56163944ccf7 <unknown>
#2 0x56163949c99e <unknown>
#3 0x56163949caa1 <unknown>
#4 0x5616394e7d64 <unknown>
#5 0x5616394c60dd <unknown>
#6 0x5616394e5006 <unknown>
#7 0x5616394c5e53 <unknown>
#8 0x56163948ddd4 <unknown>
#9 0x56163948f1de <unknown>
#10 0x561639758531 <unknown>
#11 0x56163975c455 <unknown>
#12 0x561639744f55 <unknown>
#13 0x56163975d0ef <unknown>
#14 0x56163972899f <unknown>
#15 0x561639781008 <unknown>
#16 0x5616397811d7 <unknown>
#17 0x561639793124 <unknown>
#18 0x7f680ec94ac3 <unknown>

2024-01-26 14:54:09 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 14:54:09 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x561639793f83 <unknown>
#1 0x56163944ccf7 <unknown>
#2 0x56163949c99e <unknown>
#3 0x56163949caa1 <unknown>
#4 0x5616394e7d64 <unknown>
#5 0x5616394c60dd <unknown>
#6 0x5616394e5006 <unknown>
#7 0x5616394c5e53 <unknown>
#8 0x56163948ddd4 <unknown>
#9 0x56163948f1de <unknown>
#10 0x561639758531 <unknown>
#11 0x56163975c455 <unknown>
#12 0x561639744f55 <unknown>
#13 0x56163975d0ef <unknown>
#14 0x56163972899f <unknown>
#15 0x561639781008 <unknown>
#16 0x5616397811d7 <unknown>
#17 0x561639793124 <unknown>
#18 0x7f680ec94ac3 <unknown>

2024-01-26 14:54:16 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 14:54:16 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x561639793f83 <unknown>
#1 0x56163944ccf7 <unknown>
#2 0x56163949c99e <unknown>
#3 0x56163949caa1 <unknown>
#4 0x5616394e7d64 <unknown>
#5 0x5616394c60dd <unknown>
#6 0x5616394e5006 <unknown>
#7 0x5616394c5e53 <unknown>
#8 0x56163948ddd4 <unknown>
#9 0x56163948f1de <unknown>
#10 0x561639758531 <unknown>
#11 0x56163975c455 <unknown>
#12 0x561639744f55 <unknown>
#13 0x56163975d0ef <unknown>
#14 0x56163972899f <unknown>
#15 0x561639781008 <unknown>
#16 0x5616397811d7 <unknown>
#17 0x561639793124 <unknown>
#18 0x7f680ec94ac3 <unknown>