2024-01-26 15:04:00 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fr/trade-stocks
2024-01-26 15:04:00 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55c0d139cf83 <unknown>
#1 0x55c0d1055cf7 <unknown>
#2 0x55c0d10a599e <unknown>
#3 0x55c0d10a5aa1 <unknown>
#4 0x55c0d10f0d64 <unknown>
#5 0x55c0d10cf0dd <unknown>
#6 0x55c0d10ee006 <unknown>
#7 0x55c0d10cee53 <unknown>
#8 0x55c0d1096dd4 <unknown>
#9 0x55c0d10981de <unknown>
#10 0x55c0d1361531 <unknown>
#11 0x55c0d1365455 <unknown>
#12 0x55c0d134df55 <unknown>
#13 0x55c0d13660ef <unknown>
#14 0x55c0d133199f <unknown>
#15 0x55c0d138a008 <unknown>
#16 0x55c0d138a1d7 <unknown>
#17 0x55c0d139c124 <unknown>
#18 0x7fb435494ac3 <unknown>

2024-01-26 15:04:22 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-01-26 15:04:22 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55c0d139cf83 <unknown>
#1 0x55c0d1055cf7 <unknown>
#2 0x55c0d10a599e <unknown>
#3 0x55c0d10a5aa1 <unknown>
#4 0x55c0d10f0d64 <unknown>
#5 0x55c0d10cf0dd <unknown>
#6 0x55c0d10ee006 <unknown>
#7 0x55c0d10cee53 <unknown>
#8 0x55c0d1096dd4 <unknown>
#9 0x55c0d10981de <unknown>
#10 0x55c0d1361531 <unknown>
#11 0x55c0d1365455 <unknown>
#12 0x55c0d134df55 <unknown>
#13 0x55c0d13660ef <unknown>
#14 0x55c0d133199f <unknown>
#15 0x55c0d138a008 <unknown>
#16 0x55c0d138a1d7 <unknown>
#17 0x55c0d139c124 <unknown>
#18 0x7fb435494ac3 <unknown>