2024-01-26 16:02:32 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/operar-cobre
2024-01-26 16:02:32 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5620bf3d9f83 <unknown>
#1 0x5620bf092cf7 <unknown>
#2 0x5620bf0e299e <unknown>
#3 0x5620bf0e2aa1 <unknown>
#4 0x5620bf12dd64 <unknown>
#5 0x5620bf10c0dd <unknown>
#6 0x5620bf12b006 <unknown>
#7 0x5620bf10be53 <unknown>
#8 0x5620bf0d3dd4 <unknown>
#9 0x5620bf0d51de <unknown>
#10 0x5620bf39e531 <unknown>
#11 0x5620bf3a2455 <unknown>
#12 0x5620bf38af55 <unknown>
#13 0x5620bf3a30ef <unknown>
#14 0x5620bf36e99f <unknown>
#15 0x5620bf3c7008 <unknown>
#16 0x5620bf3c71d7 <unknown>
#17 0x5620bf3d9124 <unknown>
#18 0x7fb6e9694ac3 <unknown>

2024-01-26 16:02:57 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-01-26 16:02:57 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5620bf3d9f83 <unknown>
#1 0x5620bf092cf7 <unknown>
#2 0x5620bf0e299e <unknown>
#3 0x5620bf0e2aa1 <unknown>
#4 0x5620bf12dd64 <unknown>
#5 0x5620bf10c0dd <unknown>
#6 0x5620bf12b006 <unknown>
#7 0x5620bf10be53 <unknown>
#8 0x5620bf0d3dd4 <unknown>
#9 0x5620bf0d51de <unknown>
#10 0x5620bf39e531 <unknown>
#11 0x5620bf3a2455 <unknown>
#12 0x5620bf38af55 <unknown>
#13 0x5620bf3a30ef <unknown>
#14 0x5620bf36e99f <unknown>
#15 0x5620bf3c7008 <unknown>
#16 0x5620bf3c71d7 <unknown>
#17 0x5620bf3d9124 <unknown>
#18 0x7fb6e9694ac3 <unknown>