2024-01-26 15:15:11 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/trading-strategien-leitfaden
2024-01-26 15:15:11 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5562f9133f83 <unknown>
#1 0x5562f8deccf7 <unknown>
#2 0x5562f8e3c99e <unknown>
#3 0x5562f8e3caa1 <unknown>
#4 0x5562f8e87d64 <unknown>
#5 0x5562f8e660dd <unknown>
#6 0x5562f8e85006 <unknown>
#7 0x5562f8e65e53 <unknown>
#8 0x5562f8e2ddd4 <unknown>
#9 0x5562f8e2f1de <unknown>
#10 0x5562f90f8531 <unknown>
#11 0x5562f90fc455 <unknown>
#12 0x5562f90e4f55 <unknown>
#13 0x5562f90fd0ef <unknown>
#14 0x5562f90c899f <unknown>
#15 0x5562f9121008 <unknown>
#16 0x5562f91211d7 <unknown>
#17 0x5562f9133124 <unknown>
#18 0x7f438aa94ac3 <unknown>

2024-01-26 15:15:17 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/trading-strategien-leitfaden
2024-01-26 15:15:17 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5562f9133f83 <unknown>
#1 0x5562f8deccf7 <unknown>
#2 0x5562f8e3c99e <unknown>
#3 0x5562f8e3caa1 <unknown>
#4 0x5562f8e87d64 <unknown>
#5 0x5562f8e660dd <unknown>
#6 0x5562f8e85006 <unknown>
#7 0x5562f8e65e53 <unknown>
#8 0x5562f8e2ddd4 <unknown>
#9 0x5562f8e2f1de <unknown>
#10 0x5562f90f8531 <unknown>
#11 0x5562f90fc455 <unknown>
#12 0x5562f90e4f55 <unknown>
#13 0x5562f90fd0ef <unknown>
#14 0x5562f90c899f <unknown>
#15 0x5562f9121008 <unknown>
#16 0x5562f91211d7 <unknown>
#17 0x5562f9133124 <unknown>
#18 0x7f438aa94ac3 <unknown>