2024-01-26 15:33:53 ERROR Elements not present after 0.5 seconds on page: https://capital.com/average-true-range
2024-01-26 15:33:53 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5590c57eaf83 <unknown>
#1 0x5590c54a3cf7 <unknown>
#2 0x5590c54f399e <unknown>
#3 0x5590c54f3aa1 <unknown>
#4 0x5590c553ed64 <unknown>
#5 0x5590c551d0dd <unknown>
#6 0x5590c553c006 <unknown>
#7 0x5590c551ce53 <unknown>
#8 0x5590c54e4dd4 <unknown>
#9 0x5590c54e61de <unknown>
#10 0x5590c57af531 <unknown>
#11 0x5590c57b3455 <unknown>
#12 0x5590c579bf55 <unknown>
#13 0x5590c57b40ef <unknown>
#14 0x5590c577f99f <unknown>
#15 0x5590c57d8008 <unknown>
#16 0x5590c57d81d7 <unknown>
#17 0x5590c57ea124 <unknown>
#18 0x7fd315e94ac3 <unknown>

2024-01-26 15:33:58 ERROR Elements not present after 0.5 seconds on page: https://capital.com/average-true-range
2024-01-26 15:33:58 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5590c57eaf83 <unknown>
#1 0x5590c54a3cf7 <unknown>
#2 0x5590c54f399e <unknown>
#3 0x5590c54f3aa1 <unknown>
#4 0x5590c553ed64 <unknown>
#5 0x5590c551d0dd <unknown>
#6 0x5590c553c006 <unknown>
#7 0x5590c551ce53 <unknown>
#8 0x5590c54e4dd4 <unknown>
#9 0x5590c54e61de <unknown>
#10 0x5590c57af531 <unknown>
#11 0x5590c57b3455 <unknown>
#12 0x5590c579bf55 <unknown>
#13 0x5590c57b40ef <unknown>
#14 0x5590c577f99f <unknown>
#15 0x5590c57d8008 <unknown>
#16 0x5590c57d81d7 <unknown>
#17 0x5590c57ea124 <unknown>
#18 0x7fd315e94ac3 <unknown>