2024-01-26 15:46:57 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/cfd-maerkte
2024-01-26 15:46:57 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55f6b0307f83 <unknown>
#1 0x55f6affc0cf7 <unknown>
#2 0x55f6b001099e <unknown>
#3 0x55f6b0010aa1 <unknown>
#4 0x55f6b005bd64 <unknown>
#5 0x55f6b003a0dd <unknown>
#6 0x55f6b0059006 <unknown>
#7 0x55f6b0039e53 <unknown>
#8 0x55f6b0001dd4 <unknown>
#9 0x55f6b00031de <unknown>
#10 0x55f6b02cc531 <unknown>
#11 0x55f6b02d0455 <unknown>
#12 0x55f6b02b8f55 <unknown>
#13 0x55f6b02d10ef <unknown>
#14 0x55f6b029c99f <unknown>
#15 0x55f6b02f5008 <unknown>
#16 0x55f6b02f51d7 <unknown>
#17 0x55f6b0307124 <unknown>
#18 0x7fd6b2c94ac3 <unknown>

2024-01-26 15:47:03 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/cfd-maerkte
2024-01-26 15:47:03 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55f6b0307f83 <unknown>
#1 0x55f6affc0cf7 <unknown>
#2 0x55f6b001099e <unknown>
#3 0x55f6b0010aa1 <unknown>
#4 0x55f6b005bd64 <unknown>
#5 0x55f6b003a0dd <unknown>
#6 0x55f6b0059006 <unknown>
#7 0x55f6b0039e53 <unknown>
#8 0x55f6b0001dd4 <unknown>
#9 0x55f6b00031de <unknown>
#10 0x55f6b02cc531 <unknown>
#11 0x55f6b02d0455 <unknown>
#12 0x55f6b02b8f55 <unknown>
#13 0x55f6b02d10ef <unknown>
#14 0x55f6b029c99f <unknown>
#15 0x55f6b02f5008 <unknown>
#16 0x55f6b02f51d7 <unknown>
#17 0x55f6b0307124 <unknown>
#18 0x7fd6b2c94ac3 <unknown>