2024-01-26 15:36:28 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trade-eurchf
2024-01-26 15:36:28 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55b64c1b0f83 <unknown>
#1 0x55b64be69cf7 <unknown>
#2 0x55b64beb999e <unknown>
#3 0x55b64beb9aa1 <unknown>
#4 0x55b64bf04d64 <unknown>
#5 0x55b64bee30dd <unknown>
#6 0x55b64bf02006 <unknown>
#7 0x55b64bee2e53 <unknown>
#8 0x55b64beaadd4 <unknown>
#9 0x55b64beac1de <unknown>
#10 0x55b64c175531 <unknown>
#11 0x55b64c179455 <unknown>
#12 0x55b64c161f55 <unknown>
#13 0x55b64c17a0ef <unknown>
#14 0x55b64c14599f <unknown>
#15 0x55b64c19e008 <unknown>
#16 0x55b64c19e1d7 <unknown>
#17 0x55b64c1b0124 <unknown>
#18 0x7ff8ebc94ac3 <unknown>

2024-01-26 15:36:34 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trade-eurchf
2024-01-26 15:36:34 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55b64c1b0f83 <unknown>
#1 0x55b64be69cf7 <unknown>
#2 0x55b64beb999e <unknown>
#3 0x55b64beb9aa1 <unknown>
#4 0x55b64bf04d64 <unknown>
#5 0x55b64bee30dd <unknown>
#6 0x55b64bf02006 <unknown>
#7 0x55b64bee2e53 <unknown>
#8 0x55b64beaadd4 <unknown>
#9 0x55b64beac1de <unknown>
#10 0x55b64c175531 <unknown>
#11 0x55b64c179455 <unknown>
#12 0x55b64c161f55 <unknown>
#13 0x55b64c17a0ef <unknown>
#14 0x55b64c14599f <unknown>
#15 0x55b64c19e008 <unknown>
#16 0x55b64c19e1d7 <unknown>
#17 0x55b64c1b0124 <unknown>
#18 0x7ff8ebc94ac3 <unknown>