2024-01-26 15:09:24 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fr/quest-ce-que-le-trading-de-cfd
2024-01-26 15:09:24 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x563bbf0b9f83 <unknown>
#1 0x563bbed72cf7 <unknown>
#2 0x563bbedc299e <unknown>
#3 0x563bbedc2aa1 <unknown>
#4 0x563bbee0dd64 <unknown>
#5 0x563bbedec0dd <unknown>
#6 0x563bbee0b006 <unknown>
#7 0x563bbedebe53 <unknown>
#8 0x563bbedb3dd4 <unknown>
#9 0x563bbedb51de <unknown>
#10 0x563bbf07e531 <unknown>
#11 0x563bbf082455 <unknown>
#12 0x563bbf06af55 <unknown>
#13 0x563bbf0830ef <unknown>
#14 0x563bbf04e99f <unknown>
#15 0x563bbf0a7008 <unknown>
#16 0x563bbf0a71d7 <unknown>
#17 0x563bbf0b9124 <unknown>
#18 0x7f7f86094ac3 <unknown>

2024-01-26 15:09:29 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fr/quest-ce-que-le-trading-de-cfd
2024-01-26 15:09:29 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x563bbf0b9f83 <unknown>
#1 0x563bbed72cf7 <unknown>
#2 0x563bbedc299e <unknown>
#3 0x563bbedc2aa1 <unknown>
#4 0x563bbee0dd64 <unknown>
#5 0x563bbedec0dd <unknown>
#6 0x563bbee0b006 <unknown>
#7 0x563bbedebe53 <unknown>
#8 0x563bbedb3dd4 <unknown>
#9 0x563bbedb51de <unknown>
#10 0x563bbf07e531 <unknown>
#11 0x563bbf082455 <unknown>
#12 0x563bbf06af55 <unknown>
#13 0x563bbf0830ef <unknown>
#14 0x563bbf04e99f <unknown>
#15 0x563bbf0a7008 <unknown>
#16 0x563bbf0a71d7 <unknown>
#17 0x563bbf0b9124 <unknown>
#18 0x7f7f86094ac3 <unknown>