2024-01-26 15:52:29 ERROR Elements not present after 0.5 seconds on page: https://capital.com/it/trading-su-azioni
2024-01-26 15:52:29 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x562dc5474f83 <unknown>
#1 0x562dc512dcf7 <unknown>
#2 0x562dc517d99e <unknown>
#3 0x562dc517daa1 <unknown>
#4 0x562dc51c8d64 <unknown>
#5 0x562dc51a70dd <unknown>
#6 0x562dc51c6006 <unknown>
#7 0x562dc51a6e53 <unknown>
#8 0x562dc516edd4 <unknown>
#9 0x562dc51701de <unknown>
#10 0x562dc5439531 <unknown>
#11 0x562dc543d455 <unknown>
#12 0x562dc5425f55 <unknown>
#13 0x562dc543e0ef <unknown>
#14 0x562dc540999f <unknown>
#15 0x562dc5462008 <unknown>
#16 0x562dc54621d7 <unknown>
#17 0x562dc5474124 <unknown>
#18 0x7f626c294ac3 <unknown>

2024-01-26 15:52:55 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-01-26 15:52:55 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x562dc5474f83 <unknown>
#1 0x562dc512dcf7 <unknown>
#2 0x562dc517d99e <unknown>
#3 0x562dc517daa1 <unknown>
#4 0x562dc51c8d64 <unknown>
#5 0x562dc51a70dd <unknown>
#6 0x562dc51c6006 <unknown>
#7 0x562dc51a6e53 <unknown>
#8 0x562dc516edd4 <unknown>
#9 0x562dc51701de <unknown>
#10 0x562dc5439531 <unknown>
#11 0x562dc543d455 <unknown>
#12 0x562dc5425f55 <unknown>
#13 0x562dc543e0ef <unknown>
#14 0x562dc540999f <unknown>
#15 0x562dc5462008 <unknown>
#16 0x562dc54621d7 <unknown>
#17 0x562dc5474124 <unknown>
#18 0x7f626c294ac3 <unknown>