2024-01-26 15:21:59 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/waehrungshandel
2024-01-26 15:21:59 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5561aa58ff83 <unknown>
#1 0x5561aa248cf7 <unknown>
#2 0x5561aa29899e <unknown>
#3 0x5561aa298aa1 <unknown>
#4 0x5561aa2e3d64 <unknown>
#5 0x5561aa2c20dd <unknown>
#6 0x5561aa2e1006 <unknown>
#7 0x5561aa2c1e53 <unknown>
#8 0x5561aa289dd4 <unknown>
#9 0x5561aa28b1de <unknown>
#10 0x5561aa554531 <unknown>
#11 0x5561aa558455 <unknown>
#12 0x5561aa540f55 <unknown>
#13 0x5561aa5590ef <unknown>
#14 0x5561aa52499f <unknown>
#15 0x5561aa57d008 <unknown>
#16 0x5561aa57d1d7 <unknown>
#17 0x5561aa58f124 <unknown>
#18 0x7f4454a94ac3 <unknown>

2024-01-26 15:22:05 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/waehrungshandel
2024-01-26 15:22:05 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5561aa58ff83 <unknown>
#1 0x5561aa248cf7 <unknown>
#2 0x5561aa29899e <unknown>
#3 0x5561aa298aa1 <unknown>
#4 0x5561aa2e3d64 <unknown>
#5 0x5561aa2c20dd <unknown>
#6 0x5561aa2e1006 <unknown>
#7 0x5561aa2c1e53 <unknown>
#8 0x5561aa289dd4 <unknown>
#9 0x5561aa28b1de <unknown>
#10 0x5561aa554531 <unknown>
#11 0x5561aa558455 <unknown>
#12 0x5561aa540f55 <unknown>
#13 0x5561aa5590ef <unknown>
#14 0x5561aa52499f <unknown>
#15 0x5561aa57d008 <unknown>
#16 0x5561aa57d1d7 <unknown>
#17 0x5561aa58f124 <unknown>
#18 0x7f4454a94ac3 <unknown>