2024-01-26 16:00:59 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/operar-gbp-cad
2024-01-26 16:00:59 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55b8335bef83 <unknown>
#1 0x55b833277cf7 <unknown>
#2 0x55b8332c799e <unknown>
#3 0x55b8332c7aa1 <unknown>
#4 0x55b833312d64 <unknown>
#5 0x55b8332f10dd <unknown>
#6 0x55b833310006 <unknown>
#7 0x55b8332f0e53 <unknown>
#8 0x55b8332b8dd4 <unknown>
#9 0x55b8332ba1de <unknown>
#10 0x55b833583531 <unknown>
#11 0x55b833587455 <unknown>
#12 0x55b83356ff55 <unknown>
#13 0x55b8335880ef <unknown>
#14 0x55b83355399f <unknown>
#15 0x55b8335ac008 <unknown>
#16 0x55b8335ac1d7 <unknown>
#17 0x55b8335be124 <unknown>
#18 0x7fc118094ac3 <unknown>

2024-01-26 16:01:05 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/operar-gbp-cad
2024-01-26 16:01:05 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55b8335bef83 <unknown>
#1 0x55b833277cf7 <unknown>
#2 0x55b8332c799e <unknown>
#3 0x55b8332c7aa1 <unknown>
#4 0x55b833312d64 <unknown>
#5 0x55b8332f10dd <unknown>
#6 0x55b833310006 <unknown>
#7 0x55b8332f0e53 <unknown>
#8 0x55b8332b8dd4 <unknown>
#9 0x55b8332ba1de <unknown>
#10 0x55b833583531 <unknown>
#11 0x55b833587455 <unknown>
#12 0x55b83356ff55 <unknown>
#13 0x55b8335880ef <unknown>
#14 0x55b83355399f <unknown>
#15 0x55b8335ac008 <unknown>
#16 0x55b8335ac1d7 <unknown>
#17 0x55b8335be124 <unknown>
#18 0x7fc118094ac3 <unknown>