2024-01-26 16:05:15 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/opera-google
2024-01-26 16:05:15 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55fbd17cef83 <unknown>
#1 0x55fbd1487cf7 <unknown>
#2 0x55fbd14d799e <unknown>
#3 0x55fbd14d7aa1 <unknown>
#4 0x55fbd1522d64 <unknown>
#5 0x55fbd15010dd <unknown>
#6 0x55fbd1520006 <unknown>
#7 0x55fbd1500e53 <unknown>
#8 0x55fbd14c8dd4 <unknown>
#9 0x55fbd14ca1de <unknown>
#10 0x55fbd1793531 <unknown>
#11 0x55fbd1797455 <unknown>
#12 0x55fbd177ff55 <unknown>
#13 0x55fbd17980ef <unknown>
#14 0x55fbd176399f <unknown>
#15 0x55fbd17bc008 <unknown>
#16 0x55fbd17bc1d7 <unknown>
#17 0x55fbd17ce124 <unknown>
#18 0x7f290ca94ac3 <unknown>

2024-01-26 16:05:21 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/opera-google
2024-01-26 16:05:21 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55fbd17cef83 <unknown>
#1 0x55fbd1487cf7 <unknown>
#2 0x55fbd14d799e <unknown>
#3 0x55fbd14d7aa1 <unknown>
#4 0x55fbd1522d64 <unknown>
#5 0x55fbd15010dd <unknown>
#6 0x55fbd1520006 <unknown>
#7 0x55fbd1500e53 <unknown>
#8 0x55fbd14c8dd4 <unknown>
#9 0x55fbd14ca1de <unknown>
#10 0x55fbd1793531 <unknown>
#11 0x55fbd1797455 <unknown>
#12 0x55fbd177ff55 <unknown>
#13 0x55fbd17980ef <unknown>
#14 0x55fbd176399f <unknown>
#15 0x55fbd17bc008 <unknown>
#16 0x55fbd17bc1d7 <unknown>
#17 0x55fbd17ce124 <unknown>
#18 0x7f290ca94ac3 <unknown>