2024-01-26 15:12:53 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/bollinger-baender
2024-01-26 15:12:53 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x555b2f523f83 <unknown>
#1 0x555b2f1dccf7 <unknown>
#2 0x555b2f22c99e <unknown>
#3 0x555b2f22caa1 <unknown>
#4 0x555b2f277d64 <unknown>
#5 0x555b2f2560dd <unknown>
#6 0x555b2f275006 <unknown>
#7 0x555b2f255e53 <unknown>
#8 0x555b2f21ddd4 <unknown>
#9 0x555b2f21f1de <unknown>
#10 0x555b2f4e8531 <unknown>
#11 0x555b2f4ec455 <unknown>
#12 0x555b2f4d4f55 <unknown>
#13 0x555b2f4ed0ef <unknown>
#14 0x555b2f4b899f <unknown>
#15 0x555b2f511008 <unknown>
#16 0x555b2f5111d7 <unknown>
#17 0x555b2f523124 <unknown>
#18 0x7f89d6894ac3 <unknown>

2024-01-26 15:12:59 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/bollinger-baender
2024-01-26 15:12:59 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x555b2f523f83 <unknown>
#1 0x555b2f1dccf7 <unknown>
#2 0x555b2f22c99e <unknown>
#3 0x555b2f22caa1 <unknown>
#4 0x555b2f277d64 <unknown>
#5 0x555b2f2560dd <unknown>
#6 0x555b2f275006 <unknown>
#7 0x555b2f255e53 <unknown>
#8 0x555b2f21ddd4 <unknown>
#9 0x555b2f21f1de <unknown>
#10 0x555b2f4e8531 <unknown>
#11 0x555b2f4ec455 <unknown>
#12 0x555b2f4d4f55 <unknown>
#13 0x555b2f4ed0ef <unknown>
#14 0x555b2f4b899f <unknown>
#15 0x555b2f511008 <unknown>
#16 0x555b2f5111d7 <unknown>
#17 0x555b2f523124 <unknown>
#18 0x7f89d6894ac3 <unknown>