2024-01-26 16:10:06 ERROR Elements not present after 0.5 seconds on page: https://capital.com/cn/margin-trading
2024-01-26 16:10:06 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5622c7f00f83 <unknown>
#1 0x5622c7bb9cf7 <unknown>
#2 0x5622c7c0999e <unknown>
#3 0x5622c7c09aa1 <unknown>
#4 0x5622c7c54d64 <unknown>
#5 0x5622c7c330dd <unknown>
#6 0x5622c7c52006 <unknown>
#7 0x5622c7c32e53 <unknown>
#8 0x5622c7bfadd4 <unknown>
#9 0x5622c7bfc1de <unknown>
#10 0x5622c7ec5531 <unknown>
#11 0x5622c7ec9455 <unknown>
#12 0x5622c7eb1f55 <unknown>
#13 0x5622c7eca0ef <unknown>
#14 0x5622c7e9599f <unknown>
#15 0x5622c7eee008 <unknown>
#16 0x5622c7eee1d7 <unknown>
#17 0x5622c7f00124 <unknown>
#18 0x7f52e0894ac3 <unknown>

2024-01-26 16:10:12 ERROR Elements not present after 0.5 seconds on page: https://capital.com/cn/margin-trading
2024-01-26 16:10:12 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5622c7f00f83 <unknown>
#1 0x5622c7bb9cf7 <unknown>
#2 0x5622c7c0999e <unknown>
#3 0x5622c7c09aa1 <unknown>
#4 0x5622c7c54d64 <unknown>
#5 0x5622c7c330dd <unknown>
#6 0x5622c7c52006 <unknown>
#7 0x5622c7c32e53 <unknown>
#8 0x5622c7bfadd4 <unknown>
#9 0x5622c7bfc1de <unknown>
#10 0x5622c7ec5531 <unknown>
#11 0x5622c7ec9455 <unknown>
#12 0x5622c7eb1f55 <unknown>
#13 0x5622c7eca0ef <unknown>
#14 0x5622c7e9599f <unknown>
#15 0x5622c7eee008 <unknown>
#16 0x5622c7eee1d7 <unknown>
#17 0x5622c7f00124 <unknown>
#18 0x7f52e0894ac3 <unknown>