2024-01-26 15:57:25 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/margin-trading
2024-01-26 15:57:25 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5653f7b4bf83 <unknown>
#1 0x5653f7804cf7 <unknown>
#2 0x5653f785499e <unknown>
#3 0x5653f7854aa1 <unknown>
#4 0x5653f789fd64 <unknown>
#5 0x5653f787e0dd <unknown>
#6 0x5653f789d006 <unknown>
#7 0x5653f787de53 <unknown>
#8 0x5653f7845dd4 <unknown>
#9 0x5653f78471de <unknown>
#10 0x5653f7b10531 <unknown>
#11 0x5653f7b14455 <unknown>
#12 0x5653f7afcf55 <unknown>
#13 0x5653f7b150ef <unknown>
#14 0x5653f7ae099f <unknown>
#15 0x5653f7b39008 <unknown>
#16 0x5653f7b391d7 <unknown>
#17 0x5653f7b4b124 <unknown>
#18 0x7f5790894ac3 <unknown>

2024-01-26 15:57:30 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/margin-trading
2024-01-26 15:57:30 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5653f7b4bf83 <unknown>
#1 0x5653f7804cf7 <unknown>
#2 0x5653f785499e <unknown>
#3 0x5653f7854aa1 <unknown>
#4 0x5653f789fd64 <unknown>
#5 0x5653f787e0dd <unknown>
#6 0x5653f789d006 <unknown>
#7 0x5653f787de53 <unknown>
#8 0x5653f7845dd4 <unknown>
#9 0x5653f78471de <unknown>
#10 0x5653f7b10531 <unknown>
#11 0x5653f7b14455 <unknown>
#12 0x5653f7afcf55 <unknown>
#13 0x5653f7b150ef <unknown>
#14 0x5653f7ae099f <unknown>
#15 0x5653f7b39008 <unknown>
#16 0x5653f7b391d7 <unknown>
#17 0x5653f7b4b124 <unknown>
#18 0x7f5790894ac3 <unknown>