2024-01-26 14:56:58 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fr/trading-apple
2024-01-26 14:56:58 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5654b265af83 <unknown>
#1 0x5654b2313cf7 <unknown>
#2 0x5654b236399e <unknown>
#3 0x5654b2363aa1 <unknown>
#4 0x5654b23aed64 <unknown>
#5 0x5654b238d0dd <unknown>
#6 0x5654b23ac006 <unknown>
#7 0x5654b238ce53 <unknown>
#8 0x5654b2354dd4 <unknown>
#9 0x5654b23561de <unknown>
#10 0x5654b261f531 <unknown>
#11 0x5654b2623455 <unknown>
#12 0x5654b260bf55 <unknown>
#13 0x5654b26240ef <unknown>
#14 0x5654b25ef99f <unknown>
#15 0x5654b2648008 <unknown>
#16 0x5654b26481d7 <unknown>
#17 0x5654b265a124 <unknown>
#18 0x7f340c294ac3 <unknown>

2024-01-26 14:57:04 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fr/trading-apple
2024-01-26 14:57:04 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5654b265af83 <unknown>
#1 0x5654b2313cf7 <unknown>
#2 0x5654b236399e <unknown>
#3 0x5654b2363aa1 <unknown>
#4 0x5654b23aed64 <unknown>
#5 0x5654b238d0dd <unknown>
#6 0x5654b23ac006 <unknown>
#7 0x5654b238ce53 <unknown>
#8 0x5654b2354dd4 <unknown>
#9 0x5654b23561de <unknown>
#10 0x5654b261f531 <unknown>
#11 0x5654b2623455 <unknown>
#12 0x5654b260bf55 <unknown>
#13 0x5654b26240ef <unknown>
#14 0x5654b25ef99f <unknown>
#15 0x5654b2648008 <unknown>
#16 0x5654b26481d7 <unknown>
#17 0x5654b265a124 <unknown>
#18 0x7f340c294ac3 <unknown>