2024-01-26 15:17:44 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/trade-etfs
2024-01-26 15:17:44 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55cffeab5f83 <unknown>
#1 0x55cffe76ecf7 <unknown>
#2 0x55cffe7be99e <unknown>
#3 0x55cffe7beaa1 <unknown>
#4 0x55cffe809d64 <unknown>
#5 0x55cffe7e80dd <unknown>
#6 0x55cffe807006 <unknown>
#7 0x55cffe7e7e53 <unknown>
#8 0x55cffe7afdd4 <unknown>
#9 0x55cffe7b11de <unknown>
#10 0x55cffea7a531 <unknown>
#11 0x55cffea7e455 <unknown>
#12 0x55cffea66f55 <unknown>
#13 0x55cffea7f0ef <unknown>
#14 0x55cffea4a99f <unknown>
#15 0x55cffeaa3008 <unknown>
#16 0x55cffeaa31d7 <unknown>
#17 0x55cffeab5124 <unknown>
#18 0x7ff301094ac3 <unknown>

2024-01-26 15:17:50 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/trade-etfs
2024-01-26 15:17:50 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55cffeab5f83 <unknown>
#1 0x55cffe76ecf7 <unknown>
#2 0x55cffe7be99e <unknown>
#3 0x55cffe7beaa1 <unknown>
#4 0x55cffe809d64 <unknown>
#5 0x55cffe7e80dd <unknown>
#6 0x55cffe807006 <unknown>
#7 0x55cffe7e7e53 <unknown>
#8 0x55cffe7afdd4 <unknown>
#9 0x55cffe7b11de <unknown>
#10 0x55cffea7a531 <unknown>
#11 0x55cffea7e455 <unknown>
#12 0x55cffea66f55 <unknown>
#13 0x55cffea7f0ef <unknown>
#14 0x55cffea4a99f <unknown>
#15 0x55cffeaa3008 <unknown>
#16 0x55cffeaa31d7 <unknown>
#17 0x55cffeab5124 <unknown>
#18 0x7ff301094ac3 <unknown>