2024-01-26 15:58:42 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/swing-trading
2024-01-26 15:58:42 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x56113e5c1f83 <unknown>
#1 0x56113e27acf7 <unknown>
#2 0x56113e2ca99e <unknown>
#3 0x56113e2caaa1 <unknown>
#4 0x56113e315d64 <unknown>
#5 0x56113e2f40dd <unknown>
#6 0x56113e313006 <unknown>
#7 0x56113e2f3e53 <unknown>
#8 0x56113e2bbdd4 <unknown>
#9 0x56113e2bd1de <unknown>
#10 0x56113e586531 <unknown>
#11 0x56113e58a455 <unknown>
#12 0x56113e572f55 <unknown>
#13 0x56113e58b0ef <unknown>
#14 0x56113e55699f <unknown>
#15 0x56113e5af008 <unknown>
#16 0x56113e5af1d7 <unknown>
#17 0x56113e5c1124 <unknown>
#18 0x7f8556094ac3 <unknown>

2024-01-26 15:58:47 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/swing-trading
2024-01-26 15:58:47 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x56113e5c1f83 <unknown>
#1 0x56113e27acf7 <unknown>
#2 0x56113e2ca99e <unknown>
#3 0x56113e2caaa1 <unknown>
#4 0x56113e315d64 <unknown>
#5 0x56113e2f40dd <unknown>
#6 0x56113e313006 <unknown>
#7 0x56113e2f3e53 <unknown>
#8 0x56113e2bbdd4 <unknown>
#9 0x56113e2bd1de <unknown>
#10 0x56113e586531 <unknown>
#11 0x56113e58a455 <unknown>
#12 0x56113e572f55 <unknown>
#13 0x56113e58b0ef <unknown>
#14 0x56113e55699f <unknown>
#15 0x56113e5af008 <unknown>
#16 0x56113e5af1d7 <unknown>
#17 0x56113e5c1124 <unknown>
#18 0x7f8556094ac3 <unknown>