2024-01-26 15:37:55 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/trade-netflix
2024-01-26 15:37:55 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x561900abff83 <unknown>
#1 0x561900778cf7 <unknown>
#2 0x5619007c899e <unknown>
#3 0x5619007c8aa1 <unknown>
#4 0x561900813d64 <unknown>
#5 0x5619007f20dd <unknown>
#6 0x561900811006 <unknown>
#7 0x5619007f1e53 <unknown>
#8 0x5619007b9dd4 <unknown>
#9 0x5619007bb1de <unknown>
#10 0x561900a84531 <unknown>
#11 0x561900a88455 <unknown>
#12 0x561900a70f55 <unknown>
#13 0x561900a890ef <unknown>
#14 0x561900a5499f <unknown>
#15 0x561900aad008 <unknown>
#16 0x561900aad1d7 <unknown>
#17 0x561900abf124 <unknown>
#18 0x7fea73c94ac3 <unknown>

2024-01-26 15:38:01 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/trade-netflix
2024-01-26 15:38:01 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x561900abff83 <unknown>
#1 0x561900778cf7 <unknown>
#2 0x5619007c899e <unknown>
#3 0x5619007c8aa1 <unknown>
#4 0x561900813d64 <unknown>
#5 0x5619007f20dd <unknown>
#6 0x561900811006 <unknown>
#7 0x5619007f1e53 <unknown>
#8 0x5619007b9dd4 <unknown>
#9 0x5619007bb1de <unknown>
#10 0x561900a84531 <unknown>
#11 0x561900a88455 <unknown>
#12 0x561900a70f55 <unknown>
#13 0x561900a890ef <unknown>
#14 0x561900a5499f <unknown>
#15 0x561900aad008 <unknown>
#16 0x561900aad1d7 <unknown>
#17 0x561900abf124 <unknown>
#18 0x7fea73c94ac3 <unknown>